### ISSUE TITLE
Cascade requirement file uses 'include'  instead of '-r'

### ISSUE THREAD

**Issue by nvn-nil** [thclark/python-library-template#1]
https://github.com/thclark/python-library-template/blob/8951978d1419ce1d7150bf9127af8ee7f656beb3/requirements-dev.txt#L28

**Expected:**
`pip install -r requirements-dev.txt` install all the deps from all cascaded requirement files

**What happens:**
`pip install -r requirements-dev.txt`, outputs
`ERROR: Invalid requirement: 'include docs/requirements.txt' (from line 28 of requirements-dev.txt)`

**Comment by thclark** [comment]
Fixed, thankyou @nvn-nil :)
